package com.projecteugene.validator.util

/**
 * Created by Eugene Low
 */

enum class ErrorCode {
    NOT_EQUAL_LENGTH,
    MORE_THAN_AMOUNT,
    LESS_THAN_AMOUNT,
    LENGTH_MORE_THAN_AMOUNT,
    LENGTH_LESS_THAN_AMOUNT,
    NOT_NUMERIC,
    INVALID_CODE,
    INVALID_DATE,
    NOT_EQUAL,
    IS_EMPTY,
    NO_DIGITS,
    NO_LOWERCASE,
    NO_UPPERCASE,
    NO_SPECIAL_CHARACTER,
    NOT_IMPLEMENTED,
    NOT_MALAYSIAN_PHONE_NUMBER,
    NOT_EMAIL,
    NOT_WEB_URL,
    CUSTOM
}